# Internal runner tags
gitlab_runner_docker_tag: "runner:docker"
gitlab_runner_shell_tag: "runner:shell"

# GitLab Runner package details
gitlab_runner_package_name: "gitlab-runner"
gitlab_runner_apt_key_url: "https://packages.gitlab.com/gpg.key"
gitlab_runner_apt_repo: "deb https://packages.gitlab.com/gitlab/gitlab-runner/ubuntu/ {{ ansible_distribution_release }} main"
