---
- name: configure-admins-group | Create Admins group
  ansible.builtin.group:
    name: Admins
    state: present

- name: configure-admins-group | Configure sudoers for Admins group
  ansible.builtin.template:
    src: sudoers.d-admins.j2
    dest: /etc/sudoers.d/admins
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
