---
- name: kernel | Deploy kernel hardening configuration
  ansible.builtin.copy:
    src: 99-hardening.conf
    dest: /etc/sysctl.d/99-hardening.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload sysctl

- name: kernel | Apply kernel parameters immediately
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-hardening.conf
  changed_when: false
