---
- name: ssh | Install openssh-server
  ansible.builtin.apt:
    name: openssh-server
    state: present

- name: ssh | Deploy SSH daemon configuration
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart ssh

- name: ssh | Enable and start SSH service
  ansible.builtin.systemd:
    name: ssh
    state: started
    enabled: true
